# Generated by Django 3.1.4 on 2020-12-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('title', models.CharField(max_length=32)),
                ('literature', models.FileField(upload_to='')),
            ],
        ),
    ]
